### PR TITLE
Save cloned fields as multiple values (each row in database)

### PR DESCRIPTION
**Pull request by radeno**
Based on this discussion #1215

### CODE REVIEW

**Comment by rilwis** [comment]
Hi, can you fix the coding standards as pointed here:

https://travis-ci.org/wpmetabox/meta-box/builds/363461065?utm_source=github_status&utm_medium=notification

**Comment by radeno** [comment]
Done

**Comment by rilwis** [comment]
Thanks!

**Comment by rilwis** [comment]
Closes #1215

**Pull request merged**
