### PR TITLE
Fix is_saved() when creating new post

### PR DESCRIPTION
**Pull request by radeno**
When is adding new post (any type) then is_saved() is always returned as true.
It is behavior of https://codex.wordpress.org/Function_Reference/get_metadata because every new post is autosaved, it has an ID in autosave state. get_metadata returns always empty string for non-existed key. False is returned only when object_id and meta_type doesn't exists. It never happens.

But WP has helper function to check if key really exists https://developer.wordpress.org/reference/functions/metadata_exists/

### CODE REVIEW

**Comment by rilwis** [comment]
Thanks a lot for your contribution.

I've never known about `metadata_exists`. It's really a nice piece of code.

The current logic of Meta Box is trying to get the value of the custom field, if it's an empty string or empty array (in case field saves data in multiple rows in the DB), then that means field hasn't been saved and return false. Otherwise - true.

Let me check your code and see how if it works. This is the foundation of the plugin and might affect all the checks we made for the fields and premium extensions.

**Comment by radeno** [comment]
We could define what is_saved() means.
It checks if post is saved. Not if certain meta attributeis saved.

So i think if any meta is available (persisted in database) then is_saved is false.
Any other cases are that any attribute has a value. So is_saved is true.

It is very simple logic and it works. But it could not be what user expects when defined "STD" attribute.
Standard predefined value should check every field (meta attribute) if exists and then use STD or not.

Not saved = Meta attribute doesn't exists. Use STD predefined value.
Saved and has any value except NULL (blank string is a value, it is not empty) then it has value and STD should not by applied.

**Comment by rilwis** [comment]
The whole logic around `is_saved()` is used for using the `std` value. It's not using elsewhere.

The current code works like checking `is_saved()` **per meta box**, *not per field*. So it confuses users sometimes. Ideally, it should check *per field*, but I haven't figured out a good way to do that.

This PR works great for posts/users/terms where `metadata_exists` is available. However, we also have 2 other data storage - for [custom settings page](https://metabox.io/plugins/mb-settings-page/) and [custom table](https://metabox.io/plugins/mb-custom-table/). Those storage doesn't have such a function `metadata_exists`.  I have to get data of each field to check if the value exists. If we merge this PR, then the check for those extensions is incorrect.

**Comment by rilwis** [comment]
Maybe add a check like:

```php
if ( method_exists( $field['storage'], 'exists' ) {
    // Your code
} else {
    // Old legacy code
}
```

I'll update [MB Settings Page](https://metabox.io/plugins/mb-settings-page/) and [MB Custom Table](https://metabox.io/plugins/mb-custom-table/) to add `exists` method. However, we still need to maintain the backward compatibility.

**Comment by radeno** [comment]
You are right about Settings and Custom table.

It should be some fallback for this two extensions.
I will try to handle it and update my PR.

**Comment by radeno** [comment]
@rilwis done. 
Travis CI shows errors for lines that are not affected by this PR.

**Comment by rilwis** [comment]
Everything looks good. Thanks a lot for your help!

**Comment by rilwis** [comment]
I had to revert this PR in efd24ca since the check for `metadata_exists()` does not always correct. An user reported it doesn't work with `taxonomy` field. This field doesn't store value in the post meta, thus `metadata_exists` works incorrectly.

The issue and sample code is here: https://wordpress.org/support/topic/doesnt-save-taxonomy-value/#post-10851369

**Comment by radeno** [comment]
@rilwis i see. `taxonomy` field is only virtual.
This bug shows me a new feature.

More in new Issue

**Comment by radeno** [comment]
Od my idea is little bit different. But there is a way how to fix it.
Because `taxonomy` field doesn't save any data to meta table. It should be skipped from `is_saved` checking.
This is very rare situation, because `is_saved` check all fields. So in this issue https://wordpress.org/support/topic/doesnt-save-taxonomy-value user had only one field.

Two ways how to fix it:
1. Define class property `is_virtual` to Taxonomy field class.
2. Define custom collection of fields

And then if field should be skipped it will not be processed in `is_saved` method https://github.com/radeno/meta-box/blob/a988f9c366d064f037a46c5322f7ab1729bc2fb0/inc/meta-box.php#L407

**Pull request merged**
