### PR TITLE
check if passed data is array before calling indexOf in ajaxSend

### PR DESCRIPTION
**Pull request by aboutsimon**
[issue](https://github.com/wpmetabox/meta-box/issues/1269)

### CODE REVIEW

**Comment by rilwis** [comment]
Nice fix! Can you please add some space around brackets to make the code compatible with WordPress coding standard?

```js
if ( ! Array.isArray( settings.data ) || -1 === settings.data.indexOf( 'wp_autosave' ) ) {
```

Thanks for your contribution!

**Comment by aboutsimon** [comment]
Sure.. Will this make it into the next release? I will dirty patch this for now, because we need it sooner than later, so it would be awesome to have it in the next release.

**Comment by rilwis** [comment]
Thanks for your fix.

Yes, I've merged it and it will be available in the next version.

PS: No need to squash down to one commit. It's okay.

**Comment by aboutsimon** [comment]
Awesome, thanks!

**Pull request merged**
